#!/bin/sh
# Configuracion basica del firewall UFW
echo reiniciaremos el firewall
ufw reset
echo 
echo Cerramos todo el trafico hacia nuestro equipo, nos quedaremos sin internet.
echo
sudo ufw default deny incoming
sudo ufw default deny outgoing
sudo ufw default deny routed
echo
echo Ahora permitiremos el flujo de internet con nuestras reglas
echo
ufw allow in on l0 
ufw deny in from 127.0.0.0/8
ufw allow out on enp11s0
ufw enable
ufw reload
# Nota recordar que  enp11s0 es el nombre de mi interface ,pudiera ser cualquiera.
