#!/bin/sh
# Configuracion basica del firewall UFW
echo reiniciaremos el firewall (Si esta intalado)
ufw reset
echo 
echo Cerramos todo el trafico hacia nuestro equipo, nos quedaremos sin internet.
echo
sudo ufw default deny incoming
sudo ufw default deny outgoing
sudo ufw default deny routed
echo
echo Ahora permitiremos el flujo de internet, solo a traves de la interfaz deseada
echo
ufw allow in on l0 
ufw deny in from 127.0.0.0/8
ufw allow out on enp11s0
ufw enable
ufw reload
ufw status verbose
echo
# Nota recordar que  enp11s0 es el nombre de mi interface
# Con un ifconfig sabras el nombre de tu interface 
######################### Deshabilitar IPV6 ##############################################

nano /etc/default/ufw

# /etc/default/ufw
# Set to yes to apply rules to support IPv6 (no means only IPv6 on loopback
IPV6=no
